import { anonymousPro } from "./ui/font";
import Nav from "./components/Navigation/Nav";
import { getUser } from "./lib/serverQueryFnc";
import CartContextProvider from "./components/context/cartContext";
import Footer from "./components/Navigation/footer";
import Script from "next/script";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = async ({ children }) => {
	let user = await getUser("name role access");
	//let user = false;
	console.log("ROOT LAYOUT ", user);
	return (
		<html lang="en">
			<body /* className={anonymousPro.className} */>
				<CartContextProvider>
					<div className="main_layout-container">
						{children}
						<Footer />
					</div>
					<Script src="/locoAll.js" />
				</CartContextProvider>
			</body>
		</html>
	);
};

export default RootLayout;
